# Generated by Django 3.0.4 on 2020-03-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forummain', '0003_auto_20200308_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-id']},
        ),
    ]
